spring.application.name=greet
spring.boot.admin.client.url=http://localhost:1111
spring.config.import:optional:configserver:http://localhost:2222
server.port=9001
management.endpoints.web.exposure.include=*
