spring.application.name=orderapp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/orders
spring.datasource.username=root
spring.datasource.password=Santhu@1998
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-circular-references=true

# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info
info.app.name=OrderService
info.app.description=Its for making order(creation) and order cancellation and send send event to kafka topic
info.app.version=1.0.0
info.team=Backend Team
# Show detailed health info (DB, Kafka, etc.)
management.endpoint.health.show-details=always
# Kafka bootstrap server
#spring.kafka.bootstrap-servers=localhost:9092
# Kafka producer configuration
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
server.port=8081
